<%-- 
    Document   : ajax_egresados_testimonio
    Created on : 11/07/2013, 03:26:40 PM
    Author     : Weisß
--%>

<%@page contentType="text/html" pageEncoding="UTF-8" session="false"%>
<%  int id = 0;
    if (request.getParameter("id") != null) {
        id = Integer.parseInt(request.getParameter("id"));
        if (id == 4) {
%>
<p class="negritas">David Orlando May Arzola</p>
<p class="negritas">Ingeniero en Tecnologías de la lnformación</p><br/>
<img src="${pageContext.request.contextPath}/img/servicios/egresados/testimonio_exito/01.png" alt="David Orlando May Arzola" style="float: left; margin: 0 20px 5px 0;" />
<p>Hace ya casi siete años que comencé la gran aventura de mi vida, de la que hoy puedo cosechar los frutos de esa siembra, siembra de sueños, metas, objetivos y anhelos que dirigirían el futuro que actualmente estoy viviendo.</p><br/>
<p>Todo comenzó cuando estaba terminando mis estudios de bachiller en el año 2006. Recuerdo que eran las temporadas en que las universidades del estado empezaban  a realizar sus “campañas” de promoción, en el Conalep Macuspana, lugar donde estudié profesional técnico en administración y bachiller, llegó un representante de la Universidad Tecnológica de Tabasco, un profesor de TIC – lo recuerdo muy bien porque posteriormente me dio clases – él inició su plática mostrándonos a los alumnos y alumnas las bondades de la UTTAB dentro de ellas las distintas carreras que ofrecía (que actualmente son más).</p><br/>
<p><a href="javascript:leerMas('testiminio4_link');" style="cursor: pointer;" id="testiminio4_link" class="negritas">Leer m&aacute;s (+)</a></p><br/>
<div id="testiminio4" style='display: none;'>
    <p>Era momento de tomar la gran decisión, la cual, estaría basada de acuerdo al perfil que ya tenía (administración), pero también por lo que me apasionaba en ese entonces, los idiomas. Me gustaban los idiomas, aprenderlos, escuchar a muchas personas hablar diferentes lenguas, me gustaba viajar, conocer el mundo, ese era mi sueño, poder conocer otros países y hablar sus respectivos idiomas, Francia en particular. Ya tenía mi decisión antes de llegar a casa ese mismo día en que el profesor de la UTTAB visitó el Conalep, estudiar idiomas. </p><br/>
    <p>Cuando comenté con mis papás sobre el evento sucedido en la escuela mostrándoles los folletos que me brindó el profesor de la UT y diciéndoles al mismo tiempo cuál sería mi opción profesional, a lo que me quería dedicar en un futuro, ambos, maestros de primaria, me externaron su opinión y me hicieron ver la realidad de las cosas, lo tomé como un consejo, me comentaban sobre la globalización, las nuevas tecnologías, las nuevas tendencias laborales y por supuesto sobre las capacidades que yo tenía y que sigo conservando. Escucharon entonces lo que yo tenía en mente, todos mis sueños y anhelos se los compartí, entonces mi papá, muy inteligentemente me supo orientar, supo explicarme que la vida que me tocaría vivir en un lapso de 5 a 10 años sería distinta y muy difícil, encontrar trabajo no sería tarea fácil y mucho menos si la globalización estaba presente y por qué yo, debía ser parte de ella. Como todo adolescente, no me parecían ciertas cosas e insistí con los idiomas, pero la intervención de mis padres fue tan perseverante que me hicieron ver que los idiomas están presentes en todas las demás carreras, que sería indispensable para poder trabajar hablar inglés por lo menos. Esa tarde, era la tarde en la que se tenía que definir mi futuro, los tres, sentados en la mesa, revisamos las opciones que la UT brindaba, de todas me llamó la atención Tecnologías de la Información y Comunicación, mis padres me sugirieron esa rama porque las tecnologías nunca se acabarían, decían en ese entonces, que las comunicaciones tenían que evolucionar y era evidente que el trabajo nunca se acabaría, al contrario que sería una carrera con mucho impulso y que me permitiría estar en la globalización y con mucho progreso por delante.</p><br/>
    <p>Después de ese día, comencé una ardua investigación, consulté el internet para saber más de la carrera, en qué consistía, las asignaturas que recibiría y todo lo relacionado con las Tecnologías de la Información, consideraba que me gustaban las computadoras pero no a tal grado de ser un apasionado  o geek como le llamamos comúnmente.  Al tener la información, quedé convencido que eso me gustaba, que me permitiría estar al día y a la vanguardia y desde luego tener una mejor calidad de vida. En un principio pensé que la elección de la carrera se basaba en lo que a uno le gusta para poder ejercerla con profesionalidad y gusto, pero me di cuenta que a veces no es la mejor elección  y que hay que pensar no solo en lo que nos gusta y tampoco en lo que puede suceder en el momento, sino que se tiene que ver hacia el horizonte, prevenir el futuro. Esa fue entonces la base de mi actual decisión, en aquel tiempo.</p>
    <br/>
    <p>Cuando llegó el momento de realizar los trámites para presentar el examen de admisión, lo hice con gran entusiasmo, fui a la universidad a enterarme de los procedimientos y recorrí las instalaciones, me agradó más la idea de estar allí, yo preguntaba y personal de la UT aclaraba mis dudas, ese día regresé a casa con la ficha lista para presentarme el día del examen.</p><br/>
    <p>Llegó el día en que presentaría el examen de admisión y al poco tiempo, la universidad publicó los resultados, estaba feliz porque logré el objetivo esperado, había seleccionado la carrera de Tecnologías de la Información y Comunicación en el área de Redes y Telecomunicaciones y en ella ingresé. </p>
    <br/>
    <p>Comencé mi vida universitaria en septiembre de 2006, fui conociendo nuevos ambientes, nuevas personas, nuevas estrategias y métodos de evaluación, me adapté muy rápido y conforme fue pasando el tiempo llegué hasta 5to cuatrimestre, aquí fue donde mi vida cambió. Un día normal de clases, llegó un licenciado con una convocatoria a la división de TIC, invitándonos a participar en un concurso para obtener una beca de estudios en el extranjero, nada más y nada menos que en Francia, mi sueño anhelado. Me llenó mucho de emoción, le pedí al administrativo los documentos y regresé a casa con la sonrisa de oreja a oreja.</p>
    <br/>
    <p>Ya en casa, volví a comentar con mis papás ese nuevo reto que quería enfrentar, al igual que yo se llenaron de emoción y me dijeron “adelante, si eso quieres, consíguelo”, no lo podía creer; desde luego, eso implicaría aprender un nuevo idioma y estudiar mucho más, aquí empezaba a comprobar lo que mis padres muy sabiamente me decían con respecto a los idiomas. Y pensé, nunca se equivocaron, eso me impulsó más.</p>
    <br/>
    <p>Realicé los trámites correspondientes y me entrené para presentar el primer examen, era de conocimiento general de la carrera, estudié mucho a tal grado que no dormía porque el examen sería en muy poco tiempo, viajé a Puebla a la UT de ese estado para presentar dicha evaluación, estaba nervioso pero seguro de lo que estaba haciendo… regresé a Villahermosa y tiempo después me avisaron que había pasado la prueba, salté de emoción, ahora tenía que prepararme en francés, no conocía el idioma, solo el inglés, pero eso no fue impedimento para aprenderlo y solamente tenía 4 meses para lograr el objetivo de pasar el examen de francés. Maestros mexicanos y franceses que estaban en la universidad trabajaron arduamente para que en ese corto tiempo aprendiera casi todo del idioma, esta fue la parte que más me gustó del proceso, recuerdo que pasaba horas y horas estudiando, viendo películas, escuchando música y leyendo revistas en francés, eran tantas mis ganas de estar allá que no sentía cansancio.</p>
    <br/>
    <p>El DF fue sede de la segunda evaluación, estaba más nervioso que en la primera, pues los franceses me iban a evaluar el nivel de francés, comencé con la evaluación escrita hasta llegar con la evaluación oral, recuerdo que grabaron mi conversación con el francés, era una pronunciación algo torpe, pero si me daba a entender (pues solo fueron 4 meses de estudio de la lengua), eso me dijo el evaluador al finalizar la prueba. Ya en Villahermosa seguía preparándome en el francés porque ahora era la última evaluación, aunque todavía no conocíamos los resultados, todos los que presentamos el examen en México, seguíamos estudiando… un día nos llamaron a las oficinas administrativas para darnos la noticia y afortunadamente pasé la prueba. Ese día al igual que en la primera prueba, llegué a casa y entregué la noticia a mis padres, la alegría y la emoción eran intensas.</p><br/>
    <br/>
    <p>Para el último examen, que consistía en una entrevista con un grupo de profesores franceses y mexicanos para resolver un problema y exponer los motivos de ir a estudiar a Francia, viajé a Cuernavaca, en ese viaje me acompañó la maestra francesa, aunque pareciese algo incrédulo, nos pusimos un reto, si los tres compañeros que estábamos presentando el último examen en ese entonces, pasábamos, iríamos a visitar a la maestra a su ciudad de origen, allá en Francia, eso desde luego impulsó mis ganas de seguir adelante. Así que hice mi presentación, di mis razones del porqué quería estar allá en Europa, terminó el examen y al día siguiente, regresé a Villahermosa.</p>
    <br/>
    <p>Ahora sí estaba más tenso y nervioso que nunca, era la decisión definitiva, era la noticia que cambiaría mi vida, pensé, si me voy será una nueva experiencia, pero si no me voy, aprendí una lengua más, conocí nuevas amistades y comprobé que si hago las cosas bien puedo conseguir grandes resultados. Estaba en casa esa tarde cuando envié un mensaje de texto al licenciado responsable del programa en la UT, “Lic. Bruno, ¿ya tiene los resultados del examen?” todavía me acuerdo, así le pregunté. Estaba desesperado porque no me contestaba pronto, me impacienté más y más hasta que sonó el teléfono, “qué creen, se van los tres!!!!” esas fueron sus palabras exactas, no sabía cómo reaccionar pues además estaba solo en casa con mi hermano, él fue el primero que se enteró y me abrazó muy fuerte… cuando mis padres llegaron me preguntaron si ya había resultados, les dije que todavía no… pero cuando estaban más relajados, les revelé la noticia, fue muy conmovedor …</p>
    <br/>
    <p>Me fui a Francia, conocí nuevos amigos, nuevos ambientes, nuevas costumbres, nuevos países, viví un año, un año lejos de casa pensando y pensando en lo que mis padres me repetían, nunca me arrepentí de la elección que había hecho, culminé la licencia profesional en sistemas informáticos y programas, con éxito. Traje a México nuevas experiencias, nuevas costumbres que aprendí de los franceses, ellos me mostraban cómo hacer las cosas y cómo organizarme. Comprobé que el modelo de estudio de la UT es igual al que siguen en las universidades francesas, solo que con otro idioma. No fue nada fácil, pero tampoco imposible; me esforcé tanto que mis jefes en la empresa donde realicé la estadía me llegaron a estimar, con ellos conocí la forma de operar de las empresas francesas, la tecnología que manejan y la calidad con la que trabajan. </p>
    <br/>
    <p>En el 2009, año en que regresé a mi patria, me enteré que la UT estaba promocionando las nuevas ingenierías, seguí entonces mi sendero de preparación, aunque algo complicada la entrada ya que se trataría de la primera generación, logré ingresar a la ingeniería, todo lo que aprendí en Francia lo apliqué en esta nueva etapa, resultó un éxito que ahora no lo dejo de aplicar. Culminé la ingeniería en el año 2011. Como en toda preparación profesional, como alumnos debemos aplicar los conocimientos teórico-prácticos que aprendimos en el aula, así que me dirigí al CITI Tabasco para ingresar y realizar mi estadía profesional. Todo el historial que tengo, sirvió para que en cuestión de segundos Fractalia me aceptara como practicante, desde que eso pasó, comprobé que la preparación es importante, logré culminar exitosamente en abril del 2011 y en ese mismo mes el director de Fractalia me informó que ya tenía mi espacio para poder empezar a trabajar con ellos, la alegría era inmensa. Mis padres igualmente se llenaron de satisfacción al saber que los frutos de tanto esfuerzo estaban dando resultados, a tal grado que apenas en agosto fui convocado a participar en un evento en la Ciudad de México ya que fui uno de los mejores alumnos a nivel nacional del subsistema de Universidades Tecnológicas. En total éramos quinientos ingenieros e ingenieras de la primera generación con los más altos promedios de México, el expresidente Felipe Calderón llegó al evento y en su emotivo y muy convincente mensaje nos invitó a seguir adelante, a enfrentar los nuevos retos que la vida nos pone ya que en México si hay oportunidades, solo que hay que saberlas buscar y estar preparados para ellas.</p>
    <br/>
    <p>Actualmente me encuentro laborando en proyectos en los que aplico los conocimientos que adquirí tanto en México como en Francia y lo mejor de todo es que ejerzo mi carrera con muchas ganas,  mucha perseverancia y con mucha ética y disciplina. Mis próximos proyectos, ahora que ya tengo la experiencia, serán estudiar una maestría en el extranjero, orientado siempre a las tecnologías de la información,  porque no cabe la menor duda que, entre más preparado esté uno, mejor le va en la vida y mejor serán los frutos que uno coseche. De esta manera, puedo decir que mis sueños de hablar idiomas y conocer el mundo no solamente se están cumpliendo, sino que gracias a la ayuda de mis padres se enriquecieron y con orgullo externo que, gracias a ellos soy lo que ahora soy, sin olvidar que se debe mejorar día con día.</p>

</div>
<%
} else if (id == 1) {
%>
<p class="negritas">Manuel Ramón Cárdenas Varela</p> 
<p class="negritas">Ingeniero en Tecnología Ambiental</p><br/>
<img src="${pageContext.request.contextPath}/img/servicios/egresados/testimonio_exito/02.png" alt="Manuel Ramón Cárdenas Varela" style="float: left;margin: 0 20px 5px 0;"/>
<p>Mi ingreso a la UT fue por casualidad, ya que no era mi primera opción para estudiar, mi plan original era estudiar medicina fuera del Estado en una institución militar.
    En el año 1999, me encontraba estudiando en el Colegio de Bachilleres de Jalapa, al cual llegó el lng. Manuel
    Llergo, promocionando a la Universidad Tecnológica, después de escucharlo me decidí hacer un preregistro a la carrera de TSU en Tecnología Ambiental para considerarla como una opción alterna. Decidí finalmente ingresar a esta carrera, la cual concluí satisfactoriamente, obteniendo una mención honorífica por mi desempeño académico, aunado a que fui convocado a participar en la Ciudad de México, en un evento donde invitaron a los egresados con los promedios más altos del Subsistema de Universidades Tecnológicas; donde recibimos reconocimiento por parte del entonces Presidente de la República, el Lic. Felipe Calderon Hinojosa.</p>
<p><a href="javascript:leerMas('testiminio1_link');" style="cursor: pointer;" id="testiminio1_link" class="negritas">Leer m&aacute;s (+)</a></p><br/>
<div id="testiminio1" style='display: none;'>
    <p>Como TSU me tocó trabajar en plataforma, era mi primer trabajo formal y en esas instalaciones, como novato
        en el ramo fue un gran desafío para mi pues tenía solo 21 años, después de eso, tuve otros trabajos que me
        sirvieron para aprender y cultivarme en lo laboral, esa experiencia me sirvió mucho para la Ingeniería, que
        finalmente después de 10 años la UT aperturó para la continuidad de mis estudios. Toda la
        experiencia que tuve como TSU fue de gran apoyo para estudiar pues solo confirmé lo aprendido y conocí nuevas materias en el ramo ambiental.
        También conocí nuevos amigos con los que intercambié experiencias. Actualmente me encuentro laborando en una empresa desempeñando las funciones de consultor ambiental desde hace un año y seis meses.
    </p>
</div>
<%
} else if (id == 2) {
%>
<p class="negritas">Gessell Adriana L&oacute;pez García</p> 
<p class="negritas">Ingeniera en Procesos Bioalimentarios</p><br/>
<img src="${pageContext.request.contextPath}/img/servicios/egresados/testimonio_exito/03.png" width="180" height="147" alt="Gessell Adriana L&oacute;pez García" style="float: left;margin: 0 20px 5px 0;"/>
<p>Mi experiencia al entrar a la UT es muy peculiar, yo soy técnico laboratorísta  y mi perfil estaba para química, bioquímica o química farmacobióloga QFB. Al llegar el momento de decidirme en qué universidad  inscribirme, consideré la universidad popular de la chontalpa UPCH y como segunda opción la  UT.</p><br/>
<p>Al presentar el examen de ingreso en las dos universidades terminé decidiéndome por la UT porque me gustaron sus instalaciones, infraestructura, equipos, personal capacitado, además de que la UPCH se localiza en Cárdenas y  el trayecto de mi casa hacía la universidad era lejos.  Al ver que existía en la UT la carrera de Técnico en Alimentos, algo diferente,  pero pertenecía al perfil que ya tenía en la preparatoria,  no dude en aceptarla, toda vez que existe mucho campo laboral.</p><br/>
<p><a href="javascript:leerMas('testiminio2_link');" style="cursor: pointer;" id="testiminio2_link" class="negritas">Leer m&aacute;s (+)</a></p><br/>
<div id="testiminio2" style='display: none;'>
    <p>Mi estancia en esos 2 años de carrera como Técnico Superior Universitario en Alimento, fue una experiencia grata y con mucho aprendizaje, aprendí a que no solo la persona que te enseña es tu maestro si no que puede también ser tu amigo y contar con él  como un apoyo en el crecimiento profesional, maestros capacitados, con maestría, los cuales nos motivaron a que creciéramos como profesionistas.</p>
    <br/>
    <p>La  UT me dio mi primer trabajo, en la empresa FREXPORT en Huimanguillo gracias a mis prácticas, estuve 4 meses y posteriormente me contrataron  para estar 6 meses más en el área de calidad como analista, experiencia inolvidable, donde los conocimientos que adquirí en la  UT me ayudaron  para defenderme en mi trabajo. Después trabajé en otras áreas competentes a mi perfil cuando egresé  como tecnóloga en alimentos.</p>
    <br/>
    <p>En el año 2010 se abrió la convocatoria para estudiar la ingeniería en la UT  y sorpresa para mí porque se veía muy lejano ese proyecto. Renuncié a mi trabajo que tenía como técnico laboratorista en el hospital Guadalupe y decidí entrar a estudiar la ingeniería en procesos bioalimentarios,  acepté porque ya conocía mi universidad, porque ella me formó como profesionista y me abrió las puertas al mundo laboral. </p>
    <br/>
    <p>La estancia de la carrera fue de solo 1 año 8 meses,  donde fue muy rápido el proceso, pero muy cargado, con materias de excelente categoría, en este lapso de la carrera pude conseguir el trabajo que  actualmente tengo en la coca cola.</p>
    <br/>
    <p>Recuerdo el gran cariño y amor en estos 4 años de pertenecer y ser parte de la Universidad Tecnológica de Tabasco, donde siempre estaré agradecida por la formación profesional que  recibí.</p>

</div>
<%
} else if (id == 3) {
%>
<p class="negritas">Miguel &Aacute;ngel Jim&eacute;nez Guzm&aacute;n</p> 
<p class="negritas">Ingeniero en Gesti&oacute;n de Proyectos</p><br/>
<img src="${pageContext.request.contextPath}/img/servicios/egresados/testimonio_exito/04.png" alt="Miguel &Aacute;ngel Jim&eacute;nez Guzm&aacute;n" style="float: left;margin: 0 20px 5px 0;"/>
<p>Originario de Villahermosa, Tabasco, formo parte de una familia unida, soy el 4to de 5 hermanos y siempre he tenido la oportunidad de recibir el apoyo de mis padres en su momento y posteriormente ser yo quien trabajara para sostener mis estudios, estudié mi nivel medio superior en el Plantel No. 29 del Colegio de Bachilleres de Tabasco, posteriormente ingresé a la Universidad Tecnológica de Tabasco para continuar mis estudios profesionales. Decidí ingresar porque en su momento presentaba una expectativa diferente de estudio, una metodología innovadora, cambios en la forma de la enseñanza aprendizaje, pero sobre todo, la parte práctica y las visitas de campo que se realizaban y aunque en un principio no se contaba con la infraestructura que hoy tiene,  la calidad y el nivel académico de los catedráticos ha sido siempre de los mejores, la exigencia es una de las características que nos forzaba a ser mejores, pero sobre todo a ser diferentes.</p><br/>
<p><a href="javascript:leerMas('testiminio3_link');" style="cursor: pointer;" id="testiminio3_link" class="negritas">Leer m&aacute;s (+)</a></p><br/>
<div id="testiminio3" style='display: none;'>
    <p>En un principio todo era difícil, había que realizar ciertos sacrificios si deseaba continuar mis metas, era levantarse temprano, salir a la universidad sin saber cuál sería mi hora de regreso, fue un estilo diferente, porque no solo era el conocimiento teórico sino el práctico, las visitas guiadas a empresas;  fui parte de los cambios de instalaciones, inicialmente en el Colegio Villa Rica hoy Universidad Valle del Grijalva, posteriormente el Colegio Golondrinas hoy Universidad de Sotavento, para finalmente llegar a lo que hoy son las instalaciones propias de la Universidad Tecnológica de Tabasco.</p><br/>

    <p>Viajar todos los días de Villahermosa a Parrilla en un principio era difícil, pero al final de cuentas todo cuanto tuve que hacer valió la pena, hoy  existe un sistema de transporte continuo y a todas horas, la universidad misma cuenta con sus autobuses,  ha habido un enorme crecimiento. </p><br/>

    <p>Una vez egresado de la Universidad como TSU, tuve la oportunidad de formar parte junto a otros compañeros de la universidad en una empresa de nueva creación y ser fundadores, iniciar una nueva faceta laborar, pero sobre todo, poner en práctica todo los conocimientos obtenidos, fue una experiencia que marcó mucho mi destino, porque junto con personas ya experimentadas y con muchos conocimientos, aprendí modelos y métodos desconocidos y perfeccioné lo obtenido en la universidad en su momento, pero lo que realmente me motivó a seguir, fue que sabían reconocer que no eras uno más del  montón, éramos personas con conocimientos que sabíamos hacer las cosas y estábamos en la búsqueda constante de seguir mejorando y aprendiendo. Hoy en día, podemos ver más TSU incorporados a la vida laboral, no solo en el estado sino en todo el país; posteriormente me invitaron a trabajar en el sector gubernamental donde también adquirí nuevas experiencias desarrollando actividades y funciones ad hoc a los conocimientos obtenidos en la UT, luego emigré a la Ciudad de Nogales Sonora, por invitación de un amigo para trabajar en una empresa con oficinas centrales en los Estados Unidos de Norteamérica,  donde tuve a bien desempeñar actividades de control  y de seguimiento en su mayoría, después de dos años de trabajar, decidí regresar a Tabasco y finalmente hoy día trabajo para el Instituto de Vivienda de Tabasco, lugar en el cual he desempeñado una serie de actividades diversas y he tenido la oportunidad de adquirir nuevos conocimientos y fortalecer los ya obtenidos. Con el paso del tiempo he tenido la fortuna de convertirme en un profesionista más completo, no solo experto en la generación de planes de negocio y proyectos, en la administración, sino también en el manejo de programas y software informático, diseño gráfico y editorial.</p>
    <br/>
    <p>Ahora también los nuevos ingenieros tenemos la oportunidad de estar en una organización y seguir demostrando nuestras capacidades, de que estamos hechos y como estamos formados, ser personas con sentido humano, saber hacer las cosas con eficacia, saber ser eficaces y responsables, pero sobre todo ser orgullosamente egresados de la  UT.  </p>
</div>
<%
        } else {
            out.println("Ninguna coincidencia.");
        }
    } else {
        out.println("id no valido.");
    }
%>