<%-- 
    Document   : calendario_institucional
    Created on : 25/02/2014, 10:18:40 AM
    Author     : Weiss
--%>
<%@page contentType="text/html" pageEncoding="UTF-8" session="false"%>
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>UTTAB &#124; Calendario Institucional 2014</title>
        <meta charset="UTF-8">
        <meta name="author" content="Depto. Desarrollo de sistemas UTTAB">
        <meta name="description" content="Universidad Tecnológica de Tabasco,Calendario Institucional">
        <meta name="keywords" content="tsu,educación,tecnologías,ingeniería,industrial,tecnológica,uttab,desarrollo,química,procesos,tabasco,universidad,servicios,gastronomía,page,comunicación,negocios,administración,aviso,proyectos,alumnos,escolar,mantenimiento,institucional,programa,competencias">
        <link rel="stylesheet" href="css/otras_secciones.min.css"/>
        <link rel="stylesheet" href="css/calendarioInstitucional.min.css"/>
        <link rel="stylesheet" href="js/JQuery/plugins/jquery-ui-1.10.4.custom/css/ui-lightness/jquery-ui-1.10.4.custom.min.css"/>
        <link rel="icon" href="img/favicon.ico"/>
        <!--[if IE]>
        <link rel="shortcut icon" href="img/favicon.ico"/> 
        <![endif]-->
        <!--[if lte IE 8]>
        <link rel="stylesheet" href="css/ie.min.css" >
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>
    <body>
        <%if (!(request.getParameter("d") != null)) {%>
        <jsp:include page="../includeMenu.jsp?origen=otras_secciones" flush="true"  />
        <%}%>
        <!-- Cuerpo -->
        <div id="contenedorCaleEscInte">
            <div style="width:966px; height: 129px; margin-right:34px; padding-top: 38px;font-family: 'Open Sans' !important;font-style: normal;font-weight:bold; font-size: 45px;text-align:right;color:#3A3A3A;">CALENDARIO INSTITUCIONAL<br/> 2014</div>
            <div id="datepicker_iconos">
                <form>
                    <input type="checkbox" checked="checked" onclick="repinta_todo('escolarizado', $(this));" id="r9" name="radioscat">&nbsp;&nbsp;<label style=" font-weight: bold;">MOSTRAR TODO</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r10" name="radiocat" data-clase="CeremoniaGraduacion">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/CeremoniaGraduacion.png" alt="Ceremonia de graduación" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Ceremonia de graduación</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r11" name="radiocat" data-clase="EventoBienvenidaTSU">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/EventoBienvenidaTSU.png" alt="Evento Bienvenida TSU" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Evento de bienvenida TSU</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r12" name="radiocat" data-clase="EventoBienvenidaLIC">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/EventoBienvenidaLIC.png" alt="Evento Bienvenida LIC" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Evento de bienvenida Licenciatura</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r13" name="radiocat" data-clase="DiaDelTSU">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiaDelTSU.png" alt="Día del TSU" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Día del TSU</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r14" name="radiocat" data-clase="SesionConsejoDirectivo">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/SesionConsejoDirectivo.png" alt="Sesión de Consejo Directivo" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Sesión de Consejo Directivo</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r15" name="radiocat" data-clase="SemanaDeLaSalud">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/SemanaDeLaSalud.png" alt="Semana de la salud" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Semana de la salud</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r16" name="radiocat" data-clase="CelebracionDiaDeLasMadres">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/CelebracionDiaDeLasMadres.png" alt="Celebración día de las madres" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Celebración día de las madres</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r17" name="radiocat" data-clase="CelebracionDiaDelMaestro">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/CelebracionDiaDelMaestro.png" alt="Celebración día del maestro" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Celebración día del maestro</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r18" name="radiocat" data-clase="CelebracionDiaDelTrabajadorAdministrativo">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/CelebracionDiaDelTrabajadorAdministrativo.png" alt="Celebración día del burócrata" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Celebración día del burócrata</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r19" name="radiocat" data-clase="DiaDeLaSecretaria">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiaDeLaSecretaria.png" alt="Día de la secretaria" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Día de la secretaria</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r20" name="radiocat" data-clase="SemanaDeProteccionCivil">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/SemanaDeProteccionCivil.png" alt="Semana de protección civil" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Semana de protección civil</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r21" name="radiocat" data-clase="BrindisNavidenio">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/BrindisNavidenio.png" alt="Brindis navideño" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Brindis navideño</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r22" name="radiocat" data-clase="FestivalDelTamal">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/FestivalDelTamal.png" alt="Festival del tamal" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Festival del tamal</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r23" name="radiocat" data-clase="ConsejoVinculacionPertinencia">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/ConsejoVinculacionPertinencia.png" alt="Consejo de Vinculación y Pertinencia" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Consejo de Vinculación y Pertinencia</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r24" name="radiocat" data-clase="DiaDelSindicato">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiaDelSindicato.png" alt="Día del sindicato" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Día del sindicato</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r25" name="radiocat" data-clase="InicioDeCuatrimestre">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/InicioDeCuatrimestre.png" alt="Inicio de cuatrimestre" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Inicio de cuatrimestre</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r26" name="radiocat" data-clase="FinDeCuatrimestre">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/FinDeCuatrimestre.png" alt="Fin de cuatrimestre" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Fin de cuatrimestre</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r27" name="radiocat" data-clase="Inscripciones">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/Inscripciones.png" alt="Inscripciones" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Inscripciones</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r28" name="radiocat" data-clase="Reinscripciones">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/Reinscripciones.png" alt="Reinscripciones" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Reinscripciones</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r29" name="radiocat" data-clase="Reciclaton">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/Reciclaton.png" alt="Reciclatón" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Reciclatón</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r30" name="radiocat" data-clase="EntregaRecepcion">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/EntregaRecepcion.png" alt="Entrega-recepción" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Entrega-recepción</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r31" name="radiocat" data-clase="ExpoUTTAB2014">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/ExpoUTTAB2014.png" alt="Expo UTTAB 2014" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Expo UTTAB 2014</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r32" name="radiocat" data-clase="TorneoRelampagoDeFutbol">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/TorneoRelampagoDeFutbol.png" alt="Torneo relámpago de fútbol entre planteles de educación media superior" style="vertical-align: bottom;"/><label style="text-align: left;">Torneo relámpago de fútbol</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r33" name="radiocat" data-clase="AuditoriaExterna2014">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/AuditoriaExterna2014.png" alt="Auditoría externa 2014" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Auditoría externa 2014</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r34" name="radiocat" data-clase="AuditoriaInterna2014">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/AuditoriaInterna2014.png" alt="Auditoría interna 2014" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Auditoría interna 2014</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r35" name="radiocat" data-clase="SemanaDeLaCalidad">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/SemanaDeLaCalidad.png" alt="Semana de la calidad y mejora continua" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Semana de la calidad</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r36" name="radiocat" data-clase="DiasNoLaborables">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiasNoLaborables.png" alt="Días no laborables" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Días no laborables</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r37" name="radiocat" data-clase="Vacaciones">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/Vacaciones.png" alt="Vacaciones" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Vacaciones</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r38" name="radiocat" data-clase="MuestraTalleresCulturales">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/MuestraTalleresCulturales.png" alt="Muestra de talleres culturales" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Muestra de talleres culturales</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r68" name="radiocat" data-clase="InicioTallerDeEducacion">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/InicioTallerDeEducacion.png" alt="Inicio Taller de educación ambiental" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Inicio Taller de educación ambiental</label><br/><br/>

                </form>     
            </div>

            <br/>
            <div id="datepicker"></div>
            <div id="datepicker_iconos2">
                <form>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r69" name="radiocat" data-clase="FinTallerDeEducacion">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/FinTallerDeEducacion.png" alt="Fin Taller de educación ambiental" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Fin Taller de educación ambiental</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r40" name="radiocat" data-clase="ActoCivico">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/ActoCivico.png" alt="Acto cívico" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Acto cívico</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r41" name="radiocat" data-clase="ConcursoEscoltas">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/ConcursoEscoltas.png" alt="Concurso de escoltas" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Concurso de escoltas</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r42" name="radiocat" data-clase="ExposicionPictorica">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/ExposicionPictorica.png" alt="Exposición pictórica" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Exposición pictórica</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r43" name="radiocat" data-clase="InformeDelRector">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/InformeDelRector.png" alt="Informe del rector" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Informe del rector</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r44" name="radiocat" data-clase="InformeDelGobiernadorDelEstado">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/InformeDelGobiernadorDelEstado.png" alt="Informe del gobernador del estado" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Informe del gobernador del estado</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r45" name="radiocat" data-clase="EntregaDeReportesUnidadAccesoInformacion">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/EntregaDeReportesUnidadAccesoInformacion.png" alt="Reportes a la Unidad de Acceso a la Información" style="vertical-align: bottom;"/><label style="text-align: left; ">Reportes a la Unidad de Acceso a la Información</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r46" name="radiocat" data-clase="DiaMundialDeLaTierra">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiaMundialDeLaTierra.png" alt="Día mundial de la tierra" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Día mundial de la tierra</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r47" name="radiocat" data-clase="DiaInternacionalDelLibro">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiaInternacionalDelLibro.png" alt="Día internacional del libro" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Día internacional del libro</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r70" name="radiocat" data-clase="IniciaCursoDeInduccion">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/IniciaCursoDeInduccion.png" alt="Inicia curso de inducción" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Inicia curso de inducción</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r71" name="radiocat" data-clase="FinalizaCursoDeInduccion">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/FinalizaCursoDeInduccion.png" alt="Finaliza curso de inducción" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Finaliza curso de inducción</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r48" name="radiocat" data-clase="CursoDeInduccion">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/CursoDeInduccion.png" alt="Curso de inducción" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Curso de inducción</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r49" name="radiocat" data-clase="ExpoProyectosDivisionales">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/ExpoProyectosDivisionales.png" alt="Expo proyectos divisionales" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Expo proyectos divisionales</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r50" name="radiocat" data-clase="FeriaTabasco2014">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/FeriaTabasco2014.png" alt="Feria Tabasco 2014" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Feria Tabasco 2014</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r51" name="radiocat" data-clase="InicioTorneosMultideportivos">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/InicioTorneosMultideportivos.png" alt="Inicio torneos multideportivos" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Inicio torneos multideportivos</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r52" name="radiocat" data-clase="FinTorneosMultideportivos">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/FinTorneosMultideportivos.png" alt="Fin torneos multideportivos" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Fin torneos multideportivos</label><br/><br/>
                </form>     
            </div>
            <div id="datepicker_iconos3">
                <form>

                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r53" name="radiocat" data-clase="TallerParaPadres">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/TallerParaPadres.png" alt="Taller para padres" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Taller para padres</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r54" name="radiocat" data-clase="SpellingBee">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/SpellingBee.png" alt="Spelling bee" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Spelling bee</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r55" name="radiocat" data-clase="DesfileCivicoMilitar">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DesfileCivicoMilitar.png" alt="Desfile cívico militar" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Desfile cívico militar</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r56" name="radiocat" data-clase="TorneoDeRobotica">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/TorneoDeRobotica.png" alt="Torneo de robótica" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Torneo de robótica</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r57" name="radiocat" data-clase="SegundoMaratonDeLectura2014">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/SegundoMaratonDeLectura2014.png" alt="3° maratón de lectura 2014" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>3° maratón de lectura 2014</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r58" name="radiocat" data-clase="CuartoForoRegionalDeCuerposAcademicos">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/CuartoForoRegionalDeCuerposAcademicos.png" alt="4° foro regional de cuerpos académicos" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>4° foro regional de cuerpos académicos</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r59" name="radiocat" data-clase="FestivalDeChocolate">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/FestivalDeChocolate.png" alt="Festival del chocolate" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Festival del chocolate</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r60" name="radiocat" data-clase="NacionalDeportivosUT">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/NacionalDeportivosUT.png" alt="Nacional deportivos UT" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Nacional deportivos UT</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r61" name="radiocat" data-clase="DiaMundialDelTurismo">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiaMundialDelTurismo.png" alt="Día mundial del turismo " style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Día mundial del turismo </label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r62" name="radiocat" data-clase="DiaInternacionalDelMedioAmbiente">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiaInternacionalDelMedioAmbiente.png" alt="Día internacional del medio ambiente" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Día internacional del medio ambiente</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r63" name="radiocat" data-clase="DiaInternacionalDeLaMujer">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/DiaInternacionalDeLaMujer.png" alt="Día internacional de la mujer " style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Día internacional de la mujer </label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r64" name="radiocat" data-clase="CineDebateEnIngles">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/CineDebateEnIngles.png" alt="Cine - debate en inglés" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Cine - debate en inglés</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r65" name="radiocat" data-clase="FestivalDeVerano">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/FestivalDeVerano.png" alt="Festival de verano" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Festival de verano</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r66" name="radiocat" data-clase="TraditionsAndCelebrations">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/TraditionsAndCelebrations.png" alt="Traditions and celebrations" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>Traditions and celebrations</label><br/><br/>
                    <input type="checkbox" checked="checked" onclick="repinta_calendarios('escolarizado');" id="r67" name="radiocat" data-clase="5toFestivalNavideno">&nbsp;&nbsp;<img src="img/otras_secciones/calendario_institucional/5toFestivalNavideno.png" alt="5to Festival navideños" style="vertical-align: bottom;"/>&nbsp;&nbsp;<label>5to Festival navideño</label><br/><br/>
                </form>     
            </div>
            <div class="corte"></div>
        </div>
        <!-- Cuerpo -->
        <%if (!(request.getParameter("d") != null)) {%>
        <jsp:include page="../includePie.min.jsp?origen=otras_secciones" flush="true" />
        <%} else {%>
        <script src="js/JQuery/jquery-1.11.3.min.js"></script>
        <%}%>
        <script src="js/JQuery/plugins/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.min.js"></script>
        <script src="js/otras_secciones/arreglos_calendario_institucional.min.js"></script>
        <script src="js/otras_secciones/calendario_institucional.min.js"></script>
    </body>
</html>
